version: 2
jobs:
  packer-run-build:
    docker:
    - image: hashicorp/packer:full-1.6.0
    steps:
    - checkout
    - run:
        name: Run a packer build
        command: packer build -var aws_access_key=${AWS_DEV_ACCESS_KEY_ID} -var aws_secret_key=${AWS_DEV_ACCESS_SECRET_KEY} -var aws_region=${AWS_REGION} -var source_ami=ami-085925f297f89fce1 -var ssh_username=ubuntu -var ami_name=csye6225_a4_{{timestamp}} -var ami_users=918568617781 templates/ami_aws_ec2_template.json
workflows:
  version: 2
  packer:
    jobs:
    - packer-run-build